import type { Metadata } from 'next'
import localFont from 'next/font/local'

import '@public/styles/globals.css'

import Header from '@/components/layout/client/header'
import Footer from '@/components/layout/client/footer'

const robotoRegular = localFont({
  src: '../../../public/fonts/RobotoRegular.ttf',
  variable: '--font-roboto-regular',
  weight: '100 900'
})

const openSansRegular = localFont({
  src: '../../../public/fonts/OpenSansRegular.ttf',
  variable: '--font-open-sans-regular',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Book Wise',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${robotoRegular.variable} ${openSansRegular.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
