import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@public/styles/globals.css'

const robotoRegular = localFont({
  src: [
    { path: '../../../public/fonts/Roboto/Roboto-Thin.ttf', weight: '100' },
    { path: '../../../public/fonts/Roboto/Roboto-Light.ttf', weight: '300' },
    { path: '../../../public/fonts/Roboto/Roboto-Regular.ttf', weight: '400' },
    { path: '../../../public/fonts/Roboto/Roboto-Medium.ttf', weight: '500' },
    { path: '../../../public/fonts/Roboto/Roboto-Bold.ttf', weight: '700' }
  ],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Book Wise',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${robotoRegular.variable} antialiased`}>{children}</body>
    </html>
  )
}
